//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oto_Galeri.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_GaleriEntities : DbContext
    {
        public DB_GaleriEntities()
            : base("name=DB_GaleriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAracBilgileri> TblAracBilgileri { get; set; }
        public virtual DbSet<TblKategori> TblKategori { get; set; }
        public virtual DbSet<TblMusteri> TblMusteri { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<View_3> View_3 { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<View_4> View_4 { get; set; }
    
        public virtual ObjectResult<Arac_SAT_Result> Arac_SAT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Arac_SAT_Result>("Arac_SAT");
        }
    
        public virtual ObjectResult<Musteriler_Result> Musteriler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Musteriler_Result>("Musteriler");
        }
    }
}
