//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oto_Galeri.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_3
    {
        public int MusteriID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<long> Telefon { get; set; }
        public Nullable<int> Arac { get; set; }
        public int ID { get; set; }
        public string Marka { get; set; }
        public string Plaka { get; set; }
        public Nullable<long> Kilometre { get; set; }
        public Nullable<long> Satis_Fiyati { get; set; }
        public Nullable<System.DateTime> Satis_Tarihi { get; set; }
        public string Durum { get; set; }
        public int Kategori_ID { get; set; }
        public string Kategoriler { get; set; }
    }
}
